### ISSUE TITLE
Scale and value inverted?

### ISSUE THREAD

**Issue by cgoessni** [OpenFOAM/ICengines#1]
https://github.com/OpenFOAM/ICengines/blob/48e20ccdf9e379f9ce66ca360ce1aa590831ac96/AATE/caseTemplate/constant/dynamicMeshDict#L99C1-L99C22

Shouldn't scale be 0.001 and value be the valve lift read from file? In practise, this wouldn't make a difference I guess, since a*b = b*a

**Comment by blttkgl** [comment]
That's a good point, I took the scaling function template from tutorial below, but I agree that it is a bit confusing to have the scale and value inverted.

 https://github.com/OpenFOAM/OpenFOAM-dev/blob/47fa9bc620ea79e11b5023fd33c0bfcff6cb58fa/tutorials/compressibleVoF/ballValve/constant/dynamicMeshDict#L34
